package com.mizan.enums;

public enum AuditAction {
    SIGN_UP, SIGN_IN, SIGN_OUT, TOKEN_REFRESH,
    BIOMETRIC_ENABLED, BIOMETRIC_DISABLED,
    ORDER_CREATED, ORDER_DELETED,
    PROFILE_UPDATED, API_KEY_UPDATED,
    AUTH_FAILED, RATE_LIMITED
}
